### ISSUE TITLE
Extract remote repository client to separate class

### ISSUE THREAD

**Issue by brastak** [artipie/npm-proxy-adapter#13]
Encapsulate remote repository interactions with the separate class;
Refactor unit tests - only mocks checks should stay in the NpmProxyTest

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/npm-proxy-adapter#13` is not assigned, can't get performer
