### ISSUE TITLE
Support repository path in NpmProxySlice

### ISSUE THREAD

**Issue by brastak** [artipie/npm-proxy-adapter#15]
Need to support base URL path for npm-proxy-adapter

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@brastak please check license header is wrong in `pom.xml`: https://github.com/artipie/npm-proxy-adapter/runs/632257409?check_suite_focus=true

**Comment by brastak** [comment]
@g4s8 What do you mean as "wrong"? what is checked? header and license.txt?

**Comment by brastak** [comment]
@g4s8 fixed license

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.1`

**Comment by 0crat** [comment]
Job `gh:artipie/npm-proxy-adapter#15` is not assigned, can't get performer
