### ISSUE TITLE
Implement remote repository unavailable threshold timeout

### ISSUE THREAD

**Issue by brastak** [artipie/npm-proxy-adapter#16]
When remote repository goes offline, adapter continues send requests to fetch data. Failed requests can be processed longer because of connect timeout may occurs and other server side issues. It affects on adapter - it need to handle more active requests.
Solution - to use threshold timeout for remote repo. If adapter gets coonection problem or too many HTTP 500, it marks repository as offline and doesn't try to call it for <threshold> period

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#16](https://github.com/artipie/npm-proxy-adapter/issues/16) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f84f3b8a-7020-4675-8e51-e8bc2301d372); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by olegmoz** [comment]
@brastak I suppose we need a [Circuit Breaker](https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern) here. Write our own or use something from other libraries - that a thing to decide. Another problem that require discussion is where we are going to store state of connection (say count of problems encountered recently): right now Artipie shares nothing between requests. That requires some serious changes in core design.

@g4s8 what do you think about it? What kind of objects may we store in Artipie to share between requests to same Pie?

**Comment by g4s8** [comment]
@brastak @olegmoz can we cache the connection state in a node memory? It will be possible that multi-instance setup access broken remote repository multiple times but each node will know the state of remote connection. WDYT?

**Comment by olegmoz** [comment]
@g4s8 having connection state on single node is not ideal, but better then nothing. I think we should start with it and maybe improve it later if/when we will have some solution for sharing data between nodes

**Comment by brastak** [comment]
@olegmoz @g4s8 Full-featured Circuit Breaker can over-complicate our current architecture. Do we really want it? Maybe it will be easier to store state in the storage for this adapter? Some file in the repository root, let's say `.repo-state`. It contains either `{ "status": "OK" }` or `{"status": "FAILURE", "last-failure": { "timestamp": "<timestamp>", "errorCode": <code>, "errorMsg": "<msg>" } }`. All we need - to check this before sending remote call.

From the other side, Circuit Breaker can be helpful globally in artipie - for example, we can handle S3-connection loosing

**Comment by olegmoz** [comment]
@brastak agree that we should start with something simple. Though really doubt that storing connection state in ASTO is a great idea. First, accessing it before each request will slow things down a lot. Second, out own storage might be less reliable then remote repo (S3 or other cloud storage).

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @olegmoz[/z](https://www.0crat.com/u/olegmoz) resigned from [#16](https://github.com/artipie/npm-proxy-adapter/issues/16), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The user @olegmoz[/z](https://www.0crat.com/u/olegmoz) resigned from [#16](https://github.com/artipie/npm-proxy-adapter/issues/16), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6948e16a-fe47-4e7c-9157-ba28abfc59d9, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/npm-proxy-adapter#16] declared for identity constraint of element "speed".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [699962a4-4b9f-4b01-9630-aa5f13236d5e](https://www.0crat.com/footprint/CT2E6TK9B/699962a4-4b9f-4b01-9630-aa5f13236d5e), Type: "Order was canceled"

**Comment by 0crat** [comment]
The job [#16](https://github.com/artipie/npm-proxy-adapter/issues/16) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/7718cb04-0622-47ab-8fe3-3945de5844d9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@brastak I agree with @olegmoz that storing state in the storage is a bad idea.

@g4s8 @olenagerasimova vertx comes with its own circuit breaker implementation (see https://vertx.io/docs/vertx-circuit-breaker/java/) and seems quite easy to use. Instead of reiventing the wheel, I propose to use it. It works in memory and I think for now it's enough as a starter. WDYT?

**Comment by victornoel** [comment]
@0crat wait for ARC

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/npm-proxy-adapter/issues/16#issuecomment-643599435))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#16](https://github.com/artipie/npm-proxy-adapter/issues/16) is [in scope](http://www.zerocracy.com/policy.html#14) for 15days
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @victornoel[/z](https://www.0crat.com/u/victornoel) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @brastak[/z](https://www.0crat.com/u/brastak): This user reported the ticket
    * @olegmoz[/z](https://www.0crat.com/u/olegmoz): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fnpm-proxy-adapter%2316%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
> @brastak I agree with @olegmoz that storing state in the storage is a bad idea.
> 
> @g4s8 @olenagerasimova vertx comes with its own circuit breaker implementation (see https://vertx.io/docs/vertx-circuit-breaker/java/) and seems quite easy to use. Instead of reiventing the wheel, I propose to use it. It works in memory and I think for now it's enough as a starter. WDYT?

@victornoel good, let's start with Vertx implementation

**Comment by victornoel** [comment]
@0crat wait for artipie/npm-adapter#83

**Comment by 0crat** [comment]
> @0crat wait for artipie/npm-adapter#83 ([here](https://github.com/artipie/npm-proxy-adapter/issues/16#issuecomment-650563430))

@victornoel Job [#16](https://github.com/artipie/npm-proxy-adapter/issues/16) is already on hold

**Comment by victornoel** [comment]
@brastak the PR has been merged, I think this can now be closed :)

**Comment by victornoel** [comment]
@g4s8 can we close this?

**Comment by g4s8** [comment]
@victornoel sure, sorry for the delay.
