### ISSUE TITLE
Proxy adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-proxy-adapter#2]
NPM proxy with cache and authentication support. URI for remoter repository should be configured in repo yaml config, auth settings and cache too.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/npm-proxy-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/npm-proxy-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/npm-proxy-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by brastak** [comment]
@g4s8 Please, close it

**Comment by g4s8** [comment]
@brastak thanks

**Comment by 0crat** [comment]
Job `gh:artipie/npm-proxy-adapter#2` is not assigned, can't get performer
