### ISSUE TITLE
Align storage format with NPM adapter

### ISSUE THREAD

**Issue by brastak** [artipie/npm-proxy-adapter#27]
rename package.json -> meta.json
remove ${artipie.npm_proxy_registry} prefix from tarballs - relative links should be used

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#27](https://github.com/artipie/npm-proxy-adapter/issues/27) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0d65e2bc-48f8-44a5-a07e-7449b1d33a30); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job
