### ISSUE TITLE
Implement metadata TTL

### ISSUE THREAD

**Issue by brastak** [artipie/npm-proxy-adapter#3]
In the current implementation package metadata re-read on every request to the package. Cached version is used only if request to remote repository failed.
Need to implement cache-first approach and TTL for metadata. After the package metadata is updated, cached version should be used until TTL expiration. After TTL expiration, metadata should be updated on next request

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) I'm not managing this repo, remove the [webhook](https://github.com/artipie/npm-proxy-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/npm-proxy-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:artipie/npm-proxy-adapter#3` is not assigned, can't get performer
