### ISSUE TITLE
Consider moving this repo to npm-adapter

### ISSUE THREAD

**Issue by g4s8** [artipie/npm-proxy-adapter#32]
Consider moving this code to artipie/npm-adapter repository and reuse common code. It may be two different Maven projects or just a two public `Slice` implementation: one for npm and another for npm-proxy.

**Comment by 0crat** [comment]
The job [#32](https://github.com/artipie/npm-proxy-adapter/issues/32) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a18738b8-1cfd-41eb-bac2-d610138b4ef9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @brastak[/z](https://www.0crat.com/u/brastak) resigned from [#32](https://github.com/artipie/npm-proxy-adapter/issues/32), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#32](https://github.com/artipie/npm-proxy-adapter/issues/32) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ed7d1289-4839-41f3-b7a9-44b0b68417ae); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@g4s8 I think this was incorrectly assigned to me, the job has already been done

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-proxy-adapter/issues/32#issuecomment-644519639))

@g4s8 The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#32](https://github.com/artipie/npm-proxy-adapter/issues/32), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/npm-proxy-adapter#32` is not assigned, can't get performer
