### ISSUE TITLE
NpmProxySettings.java:49-51: Connection URL should be...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-proxy-adapter#7]
The puzzle `1-07d2cbae` from #1 has to be resolved: 

https://github.com/artipie/npm-proxy-adapter/blob/2ca47f15aa87aa06809d759f1567a19f2c1f9a11/src/main/java/com/artipie/npm/proxy/NpmProxySettings.java#L49-L51

The puzzle was created by @g4s8 on 16-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1-07d2cbae` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/npm-proxy-adapter#7` is not assigned, can't get performer
