### ISSUE TITLE
NpmProxyITCase.java:80-81: Use real NPM repo instead of...

### ISSUE THREAD

**Issue by 0pdd** [artipie/npm-proxy-adapter#8]
The puzzle `1-4b827c53` from #1 has to be resolved: 

https://github.com/artipie/npm-proxy-adapter/blob/2ca47f15aa87aa06809d759f1567a19f2c1f9a11/src/test/java/com/artipie/npm/proxy/NpmProxyITCase.java#L80-L81

The puzzle was created by @g4s8 on 16-Apr-20. 

Estimate: 120 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#8](https://github.com/artipie/npm-proxy-adapter/issues/8) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/60cf87a6-c8d1-466e-a89b-45b48e2d9c2d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @brastak[/z](https://www.0crat.com/u/brastak) resigned from [#8](https://github.com/artipie/npm-proxy-adapter/issues/8), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@470ff8ad-1642-4d34-9f48-355654d6ab84, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.in.orders.remove_github_assignee
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.AssertionError: HTTP response status is not equal to 200:
403 Forbidden [https://api.github.com/repos/artipie/npm-proxy-adapter/issues/8]
Server: GitHub.com
Date: Mon, 27 Apr 2020 13:02:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 403 Forbidden
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4538
X-RateLimit-Reset: 1587994569
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: C7AC:2D2D:207D606:3687D00:5EA6D7E4

{"message":"Must have admin rights to Repository.","documentation_url":"https://developer.github.com/v3/issues/#edit-an-issue"}
Expected: HTTP response with status 200
     but: was <403 Forbidden [https://api.github.com/repos/artipie/npm-proxy-adapter/issues/8]
Server: GitHub.com
Date: Mon, 27 Apr 2020 13:02:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 403 Forbidden
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4538
X-RateLimit-Reset: 1587994569
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: C7AC:2D2D:207D606:3687D00:5EA6D7E4

{"message":"Must have admin rights to Repository.","documentation_url":"https://developer.github.com/v3/issues/#edit-an-issue"}>
org.hamcrest.MatcherAssert[20] java.lang.AssertionError: HTTP response status is not equal to 200:
403 Forbidden [https://api.github.com/repos/artipie/npm-proxy-adapter/issues/8]
Server: GitHub.com
Date: Mon, 27 Apr 2020 13:02:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 403 Forbidden
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4538
X-RateLimit-Reset: 1587994569
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: C7AC:2D2D:207D606:3687D00:5EA6D7E4

{"message":"Must have admin rights to Repository.","documentation_url":"https://developer.github.com/v3/issues/#edit-an-issue"}
Expected: HTTP response with status 200
     but: was <403 Forbidden [https://api.github.com/repos/artipie/npm-proxy-adapter/issues/8]
Server: GitHub.com
Date: Mon, 27 Apr 2020 13:02:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 403 Forbidden
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4538
X-RateLimit-Reset: 1587994569
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: C7AC:2D2D:207D606:3687D00:5EA6D7E4

{"message":"Must have admin rights to Repository.","documentation_url":"https://developer.github.com/v3/issues/#edit-an-issue"}>
```

[0.53.12](https://github.com/zerocracy/farm): CID: [9725d3a1-6727-463c-a957-6386a761a451](https://www.0crat.com/footprint/CT2E6TK9B/9725d3a1-6727-463c-a957-6386a761a451), Type: "Order was canceled"

**Comment by 0crat** [comment]
The job [#8](https://github.com/artipie/npm-proxy-adapter/issues/8) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fc503969-0f97-48f8-947b-ed23e1e715e6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-proxy-adapter/issues/8#issuecomment-620492281))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#8](https://github.com/artipie/npm-proxy-adapter/issues/8), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-proxy-adapter/issues/8#issuecomment-620492281))

@carlosmiranda Job refused in 14 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#8](https://github.com/artipie/npm-proxy-adapter/issues/8) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/46e82409-49fc-48ef-8d7f-29e7c51ce078); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-proxy-adapter/issues/8#issuecomment-620976974))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#8](https://github.com/artipie/npm-proxy-adapter/issues/8), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-proxy-adapter/issues/8#issuecomment-620976974))

@ammaratef45 Job refused in 3 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#8](https://github.com/artipie/npm-proxy-adapter/issues/8) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d59f8f9d-adb7-45a6-9b51-e7fd3e43087c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@g4s8 We need to install [verdaccio] https://github.com/verdaccio/verdaccio to the machine where we are executing the tests. How about doing that in our `Maven Build` github action?

**Comment by paulodamaso** [comment]
@0crat wait for answer

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
> @g4s8 We need to install [verdaccio] https://github.com/verdaccio/verdaccio to the machine where we are executing the tests. How about doing that in our `Maven Build` github action?

@paulodamaso I'd use testcontainers with docker image for integration tests with some external binary dependencies. WDYT?

**Comment by paulodamaso** [comment]
@g4s8 Good idea! Will use it

**Comment by 0pdd** [comment]
The puzzle `1-4b827c53` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
